name: Upload .blf file to GitHub

on:
  push:
    branches:
      - main  # Trigger action when changes are pushed to the main branch

jobs:
  upload-blf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git user
      run: |
        git config --global user.name "Your GitHub Username"
        git config --global user.email "your-email@example.com"

    - name: Add .blf file and commit
      run: |
        git add ethkeys.blf  # Add the .blf file (ensure it's in the root of the repository)
        git commit -m "Add new .blf file" || echo "No changes to commit"
        git push origin main  # Push to the main branch

    - name: Push to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides a token for actions
      run: |
        git push https://github.com/${{ github.repository }} HEAD:main
